CREATE TABLE Spolszczenia (
	ID_Spolszczenia INTEGER IDENTITY(1,1) PRIMARY KEY,
	Nazwa VARCHAR(8) UNIQUE NOT NULL
)
GO

CREATE TABLE Gatunki (
	ID_Gatunku INTEGER IDENTITY(1,1) PRIMARY KEY,
	Nazwa VARCHAR(20) UNIQUE NOT NULL
)
GO

CREATE TABLE FunkcjeObsady (
	ID_Funkcji INTEGER IDENTITY(1,1) PRIMARY KEY,
	Nazwa VARCHAR(20) UNIQUE NOT NULL
)
GO

CREATE TABLE Dystrybutorzy (
	ID_Dystrybutora INTEGER IDENTITY(1,1) PRIMARY KEY,
	Nazwa VARCHAR(50) NOT NULL,
	Telefon VARCHAR(13) NOT NULL,
	Kraj VARCHAR(30) NOT NULL,
	Siedziba VARCHAR(70) NOT NULL
)
GO

CREATE TABLE Filmy (
	ISAN CHAR(33) PRIMARY KEY,
	Tytu³ VARCHAR(100) NOT NULL,
	CzasTrwania INTEGER NOT NULL,
	DataPremiery DATE NOT NULL,
	LiczbaNagród INTEGER NOT NULL,
	CzyOskarowy BIT NOT NULL,
	ID_Gatunku INTEGER FOREIGN KEY REFERENCES Gatunki,
	ID_Dystrybutora INTEGER FOREIGN KEY REFERENCES Dystrybutorzy
)
GO

CREATE TABLE Sale (
	NumerSali INTEGER PRIMARY KEY,
	LiczbaMiejscZwyk³ych INTEGER NOT NULL,
	LiczbaMiejscVIP INTEGER NOT NULL,
	CzyObs³ugujeTrójwymiar BIT NOT NULL,
	Przegl¹d DATETIME NOT NULL
)
GO

CREATE TABLE Seanse (
	ID_Seansu INTEGER IDENTITY(1,1) PRIMARY KEY,
	CzyTrójwymiar BIT NOT NULL,
	Przychód INTEGER NOT NULL,
	Data DATE NOT NULL,
	Godzina TIME NOT NULL,
	Widownia INTEGER NOT NULL,
	ISAN_Filmu CHAR(33) FOREIGN KEY REFERENCES Filmy,
	NumerSali INTEGER FOREIGN KEY REFERENCES Sale,
	ID_Spolszczenia INTEGER FOREIGN KEY REFERENCES Spolszczenia,
)
GO

CREATE TABLE Cz³onkowieObsady(
	ID_Cz³onkaObsady INTEGER IDENTITY(1,1) PRIMARY KEY,
	Imiê VARCHAR(20) NOT NULL,
	Nazwisko VARCHAR(40) NOT NULL,
	P³eæ VARCHAR(9) NOT NULL,
	CzyLaureatOskara BIT NOT NULL
)
GO

CREATE TABLE Cz³onkostwo(
	ID_Cz³onkaObsady INTEGER FOREIGN KEY REFERENCES Cz³onkowieObsady,
	ISAN_Filmu CHAR(33) FOREIGN KEY REFERENCES Filmy,
	ID_Funkcji INTEGER FOREIGN KEY REFERENCES FunkcjeObsady,
	PRIMARY KEY (ID_Cz³onkaObsady, ISAN_Filmu, ID_Funkcji)
)
GO